################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../GTK/curl/lib/amigaos.c \
../GTK/curl/lib/asyn-ares.c \
../GTK/curl/lib/asyn-thread.c \
../GTK/curl/lib/base64.c \
../GTK/curl/lib/conncache.c \
../GTK/curl/lib/connect.c \
../GTK/curl/lib/content_encoding.c \
../GTK/curl/lib/cookie.c \
../GTK/curl/lib/curl_addrinfo.c \
../GTK/curl/lib/curl_des.c \
../GTK/curl/lib/curl_endian.c \
../GTK/curl/lib/curl_fnmatch.c \
../GTK/curl/lib/curl_gethostname.c \
../GTK/curl/lib/curl_gssapi.c \
../GTK/curl/lib/curl_memrchr.c \
../GTK/curl/lib/curl_multibyte.c \
../GTK/curl/lib/curl_ntlm.c \
../GTK/curl/lib/curl_ntlm_core.c \
../GTK/curl/lib/curl_ntlm_msgs.c \
../GTK/curl/lib/curl_ntlm_wb.c \
../GTK/curl/lib/curl_rtmp.c \
../GTK/curl/lib/curl_sasl.c \
../GTK/curl/lib/curl_sasl_gssapi.c \
../GTK/curl/lib/curl_sasl_sspi.c \
../GTK/curl/lib/curl_sspi.c \
../GTK/curl/lib/curl_threads.c \
../GTK/curl/lib/dict.c \
../GTK/curl/lib/dotdot.c \
../GTK/curl/lib/easy.c \
../GTK/curl/lib/escape.c \
../GTK/curl/lib/file.c \
../GTK/curl/lib/fileinfo.c \
../GTK/curl/lib/formdata.c \
../GTK/curl/lib/ftp.c \
../GTK/curl/lib/ftplistparser.c \
../GTK/curl/lib/getenv.c \
../GTK/curl/lib/getinfo.c \
../GTK/curl/lib/gopher.c \
../GTK/curl/lib/hash.c \
../GTK/curl/lib/hmac.c \
../GTK/curl/lib/hostasyn.c \
../GTK/curl/lib/hostcheck.c \
../GTK/curl/lib/hostip.c \
../GTK/curl/lib/hostip4.c \
../GTK/curl/lib/hostip6.c \
../GTK/curl/lib/hostsyn.c \
../GTK/curl/lib/http.c \
../GTK/curl/lib/http2.c \
../GTK/curl/lib/http_chunks.c \
../GTK/curl/lib/http_digest.c \
../GTK/curl/lib/http_negotiate.c \
../GTK/curl/lib/http_negotiate_sspi.c \
../GTK/curl/lib/http_proxy.c \
../GTK/curl/lib/idn_win32.c \
../GTK/curl/lib/if2ip.c \
../GTK/curl/lib/imap.c \
../GTK/curl/lib/inet_ntop.c \
../GTK/curl/lib/inet_pton.c \
../GTK/curl/lib/krb5.c \
../GTK/curl/lib/ldap.c \
../GTK/curl/lib/llist.c \
../GTK/curl/lib/md4.c \
../GTK/curl/lib/md5.c \
../GTK/curl/lib/memdebug.c \
../GTK/curl/lib/mprintf.c \
../GTK/curl/lib/multi.c \
../GTK/curl/lib/netrc.c \
../GTK/curl/lib/non-ascii.c \
../GTK/curl/lib/nonblock.c \
../GTK/curl/lib/nwlib.c \
../GTK/curl/lib/nwos.c \
../GTK/curl/lib/openldap.c \
../GTK/curl/lib/parsedate.c \
../GTK/curl/lib/pingpong.c \
../GTK/curl/lib/pipeline.c \
../GTK/curl/lib/pop3.c \
../GTK/curl/lib/progress.c \
../GTK/curl/lib/rawstr.c \
../GTK/curl/lib/rtsp.c \
../GTK/curl/lib/security.c \
../GTK/curl/lib/select.c \
../GTK/curl/lib/sendf.c \
../GTK/curl/lib/share.c \
../GTK/curl/lib/slist.c \
../GTK/curl/lib/smb.c \
../GTK/curl/lib/smtp.c \
../GTK/curl/lib/socks.c \
../GTK/curl/lib/socks_gssapi.c \
../GTK/curl/lib/socks_sspi.c \
../GTK/curl/lib/speedcheck.c \
../GTK/curl/lib/splay.c \
../GTK/curl/lib/ssh.c \
../GTK/curl/lib/strdup.c \
../GTK/curl/lib/strequal.c \
../GTK/curl/lib/strerror.c \
../GTK/curl/lib/strtok.c \
../GTK/curl/lib/strtoofft.c \
../GTK/curl/lib/telnet.c \
../GTK/curl/lib/tftp.c \
../GTK/curl/lib/timeval.c \
../GTK/curl/lib/transfer.c \
../GTK/curl/lib/url.c \
../GTK/curl/lib/version.c \
../GTK/curl/lib/warnless.c \
../GTK/curl/lib/wildcard.c \
../GTK/curl/lib/x509asn1.c 

OBJS += \
./GTK/curl/lib/amigaos.o \
./GTK/curl/lib/asyn-ares.o \
./GTK/curl/lib/asyn-thread.o \
./GTK/curl/lib/base64.o \
./GTK/curl/lib/conncache.o \
./GTK/curl/lib/connect.o \
./GTK/curl/lib/content_encoding.o \
./GTK/curl/lib/cookie.o \
./GTK/curl/lib/curl_addrinfo.o \
./GTK/curl/lib/curl_des.o \
./GTK/curl/lib/curl_endian.o \
./GTK/curl/lib/curl_fnmatch.o \
./GTK/curl/lib/curl_gethostname.o \
./GTK/curl/lib/curl_gssapi.o \
./GTK/curl/lib/curl_memrchr.o \
./GTK/curl/lib/curl_multibyte.o \
./GTK/curl/lib/curl_ntlm.o \
./GTK/curl/lib/curl_ntlm_core.o \
./GTK/curl/lib/curl_ntlm_msgs.o \
./GTK/curl/lib/curl_ntlm_wb.o \
./GTK/curl/lib/curl_rtmp.o \
./GTK/curl/lib/curl_sasl.o \
./GTK/curl/lib/curl_sasl_gssapi.o \
./GTK/curl/lib/curl_sasl_sspi.o \
./GTK/curl/lib/curl_sspi.o \
./GTK/curl/lib/curl_threads.o \
./GTK/curl/lib/dict.o \
./GTK/curl/lib/dotdot.o \
./GTK/curl/lib/easy.o \
./GTK/curl/lib/escape.o \
./GTK/curl/lib/file.o \
./GTK/curl/lib/fileinfo.o \
./GTK/curl/lib/formdata.o \
./GTK/curl/lib/ftp.o \
./GTK/curl/lib/ftplistparser.o \
./GTK/curl/lib/getenv.o \
./GTK/curl/lib/getinfo.o \
./GTK/curl/lib/gopher.o \
./GTK/curl/lib/hash.o \
./GTK/curl/lib/hmac.o \
./GTK/curl/lib/hostasyn.o \
./GTK/curl/lib/hostcheck.o \
./GTK/curl/lib/hostip.o \
./GTK/curl/lib/hostip4.o \
./GTK/curl/lib/hostip6.o \
./GTK/curl/lib/hostsyn.o \
./GTK/curl/lib/http.o \
./GTK/curl/lib/http2.o \
./GTK/curl/lib/http_chunks.o \
./GTK/curl/lib/http_digest.o \
./GTK/curl/lib/http_negotiate.o \
./GTK/curl/lib/http_negotiate_sspi.o \
./GTK/curl/lib/http_proxy.o \
./GTK/curl/lib/idn_win32.o \
./GTK/curl/lib/if2ip.o \
./GTK/curl/lib/imap.o \
./GTK/curl/lib/inet_ntop.o \
./GTK/curl/lib/inet_pton.o \
./GTK/curl/lib/krb5.o \
./GTK/curl/lib/ldap.o \
./GTK/curl/lib/llist.o \
./GTK/curl/lib/md4.o \
./GTK/curl/lib/md5.o \
./GTK/curl/lib/memdebug.o \
./GTK/curl/lib/mprintf.o \
./GTK/curl/lib/multi.o \
./GTK/curl/lib/netrc.o \
./GTK/curl/lib/non-ascii.o \
./GTK/curl/lib/nonblock.o \
./GTK/curl/lib/nwlib.o \
./GTK/curl/lib/nwos.o \
./GTK/curl/lib/openldap.o \
./GTK/curl/lib/parsedate.o \
./GTK/curl/lib/pingpong.o \
./GTK/curl/lib/pipeline.o \
./GTK/curl/lib/pop3.o \
./GTK/curl/lib/progress.o \
./GTK/curl/lib/rawstr.o \
./GTK/curl/lib/rtsp.o \
./GTK/curl/lib/security.o \
./GTK/curl/lib/select.o \
./GTK/curl/lib/sendf.o \
./GTK/curl/lib/share.o \
./GTK/curl/lib/slist.o \
./GTK/curl/lib/smb.o \
./GTK/curl/lib/smtp.o \
./GTK/curl/lib/socks.o \
./GTK/curl/lib/socks_gssapi.o \
./GTK/curl/lib/socks_sspi.o \
./GTK/curl/lib/speedcheck.o \
./GTK/curl/lib/splay.o \
./GTK/curl/lib/ssh.o \
./GTK/curl/lib/strdup.o \
./GTK/curl/lib/strequal.o \
./GTK/curl/lib/strerror.o \
./GTK/curl/lib/strtok.o \
./GTK/curl/lib/strtoofft.o \
./GTK/curl/lib/telnet.o \
./GTK/curl/lib/tftp.o \
./GTK/curl/lib/timeval.o \
./GTK/curl/lib/transfer.o \
./GTK/curl/lib/url.o \
./GTK/curl/lib/version.o \
./GTK/curl/lib/warnless.o \
./GTK/curl/lib/wildcard.o \
./GTK/curl/lib/x509asn1.o 

C_DEPS += \
./GTK/curl/lib/amigaos.d \
./GTK/curl/lib/asyn-ares.d \
./GTK/curl/lib/asyn-thread.d \
./GTK/curl/lib/base64.d \
./GTK/curl/lib/conncache.d \
./GTK/curl/lib/connect.d \
./GTK/curl/lib/content_encoding.d \
./GTK/curl/lib/cookie.d \
./GTK/curl/lib/curl_addrinfo.d \
./GTK/curl/lib/curl_des.d \
./GTK/curl/lib/curl_endian.d \
./GTK/curl/lib/curl_fnmatch.d \
./GTK/curl/lib/curl_gethostname.d \
./GTK/curl/lib/curl_gssapi.d \
./GTK/curl/lib/curl_memrchr.d \
./GTK/curl/lib/curl_multibyte.d \
./GTK/curl/lib/curl_ntlm.d \
./GTK/curl/lib/curl_ntlm_core.d \
./GTK/curl/lib/curl_ntlm_msgs.d \
./GTK/curl/lib/curl_ntlm_wb.d \
./GTK/curl/lib/curl_rtmp.d \
./GTK/curl/lib/curl_sasl.d \
./GTK/curl/lib/curl_sasl_gssapi.d \
./GTK/curl/lib/curl_sasl_sspi.d \
./GTK/curl/lib/curl_sspi.d \
./GTK/curl/lib/curl_threads.d \
./GTK/curl/lib/dict.d \
./GTK/curl/lib/dotdot.d \
./GTK/curl/lib/easy.d \
./GTK/curl/lib/escape.d \
./GTK/curl/lib/file.d \
./GTK/curl/lib/fileinfo.d \
./GTK/curl/lib/formdata.d \
./GTK/curl/lib/ftp.d \
./GTK/curl/lib/ftplistparser.d \
./GTK/curl/lib/getenv.d \
./GTK/curl/lib/getinfo.d \
./GTK/curl/lib/gopher.d \
./GTK/curl/lib/hash.d \
./GTK/curl/lib/hmac.d \
./GTK/curl/lib/hostasyn.d \
./GTK/curl/lib/hostcheck.d \
./GTK/curl/lib/hostip.d \
./GTK/curl/lib/hostip4.d \
./GTK/curl/lib/hostip6.d \
./GTK/curl/lib/hostsyn.d \
./GTK/curl/lib/http.d \
./GTK/curl/lib/http2.d \
./GTK/curl/lib/http_chunks.d \
./GTK/curl/lib/http_digest.d \
./GTK/curl/lib/http_negotiate.d \
./GTK/curl/lib/http_negotiate_sspi.d \
./GTK/curl/lib/http_proxy.d \
./GTK/curl/lib/idn_win32.d \
./GTK/curl/lib/if2ip.d \
./GTK/curl/lib/imap.d \
./GTK/curl/lib/inet_ntop.d \
./GTK/curl/lib/inet_pton.d \
./GTK/curl/lib/krb5.d \
./GTK/curl/lib/ldap.d \
./GTK/curl/lib/llist.d \
./GTK/curl/lib/md4.d \
./GTK/curl/lib/md5.d \
./GTK/curl/lib/memdebug.d \
./GTK/curl/lib/mprintf.d \
./GTK/curl/lib/multi.d \
./GTK/curl/lib/netrc.d \
./GTK/curl/lib/non-ascii.d \
./GTK/curl/lib/nonblock.d \
./GTK/curl/lib/nwlib.d \
./GTK/curl/lib/nwos.d \
./GTK/curl/lib/openldap.d \
./GTK/curl/lib/parsedate.d \
./GTK/curl/lib/pingpong.d \
./GTK/curl/lib/pipeline.d \
./GTK/curl/lib/pop3.d \
./GTK/curl/lib/progress.d \
./GTK/curl/lib/rawstr.d \
./GTK/curl/lib/rtsp.d \
./GTK/curl/lib/security.d \
./GTK/curl/lib/select.d \
./GTK/curl/lib/sendf.d \
./GTK/curl/lib/share.d \
./GTK/curl/lib/slist.d \
./GTK/curl/lib/smb.d \
./GTK/curl/lib/smtp.d \
./GTK/curl/lib/socks.d \
./GTK/curl/lib/socks_gssapi.d \
./GTK/curl/lib/socks_sspi.d \
./GTK/curl/lib/speedcheck.d \
./GTK/curl/lib/splay.d \
./GTK/curl/lib/ssh.d \
./GTK/curl/lib/strdup.d \
./GTK/curl/lib/strequal.d \
./GTK/curl/lib/strerror.d \
./GTK/curl/lib/strtok.d \
./GTK/curl/lib/strtoofft.d \
./GTK/curl/lib/telnet.d \
./GTK/curl/lib/tftp.d \
./GTK/curl/lib/timeval.d \
./GTK/curl/lib/transfer.d \
./GTK/curl/lib/url.d \
./GTK/curl/lib/version.d \
./GTK/curl/lib/warnless.d \
./GTK/curl/lib/wildcard.d \
./GTK/curl/lib/x509asn1.d 


# Each subdirectory must supply rules for building sources it contributes
GTK/curl/lib/%.o: ../GTK/curl/lib/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	arm-linux-gnueabihf-gcc -I/home/snelso/rpi/rootfs/usr/include/gtk-3.0 -I/home/snelso/capstone-workspace/ABRSEmbeddedDev/Teensy -I/home/snelso/rpi/rootfs/usr/include/at-spi2-atk/2.0 -I/home/snelso/rpi/rootfs/usr/include/atk-1.0 -I/home/snelso/rpi/rootfs/usr/include/harfbuzz -I/home/snelso/rpi/rootfs/usr/include/libpng12 -I/home/snelso/rpi/rootfs/usr/include/pixman-1 -I/home/snelso/rpi/rootfs/usr/include/gdk-pixbuf-2.0 -I/home/snelso/rpi/rootfs/usr/include/cairo -I/home/snelso/rpi/rootfs/usr/include/freetype2 -I/home/snelso/rpi/rootfs/usr/include/gio-unix-2.0/ -I/home/snelso/rpi/rootfs/usr/include/pango-1.0 -I/home/snelso/rpi/rootfs/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/home/snelso/rpi/rootfs/usr/include/glib-2.0 -I/home/snelso/capstone-workspace/ABRSEmbeddedDev/Deps/wiringPi/wiringPi-from-pi -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"  -lpthread -lwiringPi
	@echo 'Finished building: $<'
	@echo ' '


