################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../GTK/curl/tests/libtest/chkhostname.c \
../GTK/curl/tests/libtest/first.c \
../GTK/curl/tests/libtest/lib1500.c \
../GTK/curl/tests/libtest/lib1501.c \
../GTK/curl/tests/libtest/lib1502.c \
../GTK/curl/tests/libtest/lib1506.c \
../GTK/curl/tests/libtest/lib1507.c \
../GTK/curl/tests/libtest/lib1508.c \
../GTK/curl/tests/libtest/lib1509.c \
../GTK/curl/tests/libtest/lib1510.c \
../GTK/curl/tests/libtest/lib1511.c \
../GTK/curl/tests/libtest/lib1512.c \
../GTK/curl/tests/libtest/lib1513.c \
../GTK/curl/tests/libtest/lib1514.c \
../GTK/curl/tests/libtest/lib1515.c \
../GTK/curl/tests/libtest/lib1520.c \
../GTK/curl/tests/libtest/lib1525.c \
../GTK/curl/tests/libtest/lib1526.c \
../GTK/curl/tests/libtest/lib1527.c \
../GTK/curl/tests/libtest/lib1528.c \
../GTK/curl/tests/libtest/lib1529.c \
../GTK/curl/tests/libtest/lib1530.c \
../GTK/curl/tests/libtest/lib1531.c \
../GTK/curl/tests/libtest/lib1900.c \
../GTK/curl/tests/libtest/lib500.c \
../GTK/curl/tests/libtest/lib501.c \
../GTK/curl/tests/libtest/lib502.c \
../GTK/curl/tests/libtest/lib503.c \
../GTK/curl/tests/libtest/lib504.c \
../GTK/curl/tests/libtest/lib505.c \
../GTK/curl/tests/libtest/lib506.c \
../GTK/curl/tests/libtest/lib507.c \
../GTK/curl/tests/libtest/lib508.c \
../GTK/curl/tests/libtest/lib509.c \
../GTK/curl/tests/libtest/lib510.c \
../GTK/curl/tests/libtest/lib511.c \
../GTK/curl/tests/libtest/lib512.c \
../GTK/curl/tests/libtest/lib513.c \
../GTK/curl/tests/libtest/lib514.c \
../GTK/curl/tests/libtest/lib515.c \
../GTK/curl/tests/libtest/lib516.c \
../GTK/curl/tests/libtest/lib517.c \
../GTK/curl/tests/libtest/lib518.c \
../GTK/curl/tests/libtest/lib519.c \
../GTK/curl/tests/libtest/lib520.c \
../GTK/curl/tests/libtest/lib521.c \
../GTK/curl/tests/libtest/lib523.c \
../GTK/curl/tests/libtest/lib524.c \
../GTK/curl/tests/libtest/lib525.c \
../GTK/curl/tests/libtest/lib526.c \
../GTK/curl/tests/libtest/lib530.c \
../GTK/curl/tests/libtest/lib533.c \
../GTK/curl/tests/libtest/lib536.c \
../GTK/curl/tests/libtest/lib537.c \
../GTK/curl/tests/libtest/lib539.c \
../GTK/curl/tests/libtest/lib540.c \
../GTK/curl/tests/libtest/lib541.c \
../GTK/curl/tests/libtest/lib542.c \
../GTK/curl/tests/libtest/lib543.c \
../GTK/curl/tests/libtest/lib544.c \
../GTK/curl/tests/libtest/lib547.c \
../GTK/curl/tests/libtest/lib549.c \
../GTK/curl/tests/libtest/lib552.c \
../GTK/curl/tests/libtest/lib553.c \
../GTK/curl/tests/libtest/lib554.c \
../GTK/curl/tests/libtest/lib555.c \
../GTK/curl/tests/libtest/lib556.c \
../GTK/curl/tests/libtest/lib557.c \
../GTK/curl/tests/libtest/lib558.c \
../GTK/curl/tests/libtest/lib560.c \
../GTK/curl/tests/libtest/lib562.c \
../GTK/curl/tests/libtest/lib564.c \
../GTK/curl/tests/libtest/lib566.c \
../GTK/curl/tests/libtest/lib567.c \
../GTK/curl/tests/libtest/lib568.c \
../GTK/curl/tests/libtest/lib569.c \
../GTK/curl/tests/libtest/lib570.c \
../GTK/curl/tests/libtest/lib571.c \
../GTK/curl/tests/libtest/lib572.c \
../GTK/curl/tests/libtest/lib573.c \
../GTK/curl/tests/libtest/lib574.c \
../GTK/curl/tests/libtest/lib575.c \
../GTK/curl/tests/libtest/lib576.c \
../GTK/curl/tests/libtest/lib578.c \
../GTK/curl/tests/libtest/lib579.c \
../GTK/curl/tests/libtest/lib582.c \
../GTK/curl/tests/libtest/lib583.c \
../GTK/curl/tests/libtest/lib586.c \
../GTK/curl/tests/libtest/lib590.c \
../GTK/curl/tests/libtest/lib591.c \
../GTK/curl/tests/libtest/lib597.c \
../GTK/curl/tests/libtest/lib598.c \
../GTK/curl/tests/libtest/lib599.c \
../GTK/curl/tests/libtest/libauthretry.c \
../GTK/curl/tests/libtest/libntlmconnect.c \
../GTK/curl/tests/libtest/sethostname.c \
../GTK/curl/tests/libtest/testtrace.c \
../GTK/curl/tests/libtest/testutil.c 

OBJS += \
./GTK/curl/tests/libtest/chkhostname.o \
./GTK/curl/tests/libtest/first.o \
./GTK/curl/tests/libtest/lib1500.o \
./GTK/curl/tests/libtest/lib1501.o \
./GTK/curl/tests/libtest/lib1502.o \
./GTK/curl/tests/libtest/lib1506.o \
./GTK/curl/tests/libtest/lib1507.o \
./GTK/curl/tests/libtest/lib1508.o \
./GTK/curl/tests/libtest/lib1509.o \
./GTK/curl/tests/libtest/lib1510.o \
./GTK/curl/tests/libtest/lib1511.o \
./GTK/curl/tests/libtest/lib1512.o \
./GTK/curl/tests/libtest/lib1513.o \
./GTK/curl/tests/libtest/lib1514.o \
./GTK/curl/tests/libtest/lib1515.o \
./GTK/curl/tests/libtest/lib1520.o \
./GTK/curl/tests/libtest/lib1525.o \
./GTK/curl/tests/libtest/lib1526.o \
./GTK/curl/tests/libtest/lib1527.o \
./GTK/curl/tests/libtest/lib1528.o \
./GTK/curl/tests/libtest/lib1529.o \
./GTK/curl/tests/libtest/lib1530.o \
./GTK/curl/tests/libtest/lib1531.o \
./GTK/curl/tests/libtest/lib1900.o \
./GTK/curl/tests/libtest/lib500.o \
./GTK/curl/tests/libtest/lib501.o \
./GTK/curl/tests/libtest/lib502.o \
./GTK/curl/tests/libtest/lib503.o \
./GTK/curl/tests/libtest/lib504.o \
./GTK/curl/tests/libtest/lib505.o \
./GTK/curl/tests/libtest/lib506.o \
./GTK/curl/tests/libtest/lib507.o \
./GTK/curl/tests/libtest/lib508.o \
./GTK/curl/tests/libtest/lib509.o \
./GTK/curl/tests/libtest/lib510.o \
./GTK/curl/tests/libtest/lib511.o \
./GTK/curl/tests/libtest/lib512.o \
./GTK/curl/tests/libtest/lib513.o \
./GTK/curl/tests/libtest/lib514.o \
./GTK/curl/tests/libtest/lib515.o \
./GTK/curl/tests/libtest/lib516.o \
./GTK/curl/tests/libtest/lib517.o \
./GTK/curl/tests/libtest/lib518.o \
./GTK/curl/tests/libtest/lib519.o \
./GTK/curl/tests/libtest/lib520.o \
./GTK/curl/tests/libtest/lib521.o \
./GTK/curl/tests/libtest/lib523.o \
./GTK/curl/tests/libtest/lib524.o \
./GTK/curl/tests/libtest/lib525.o \
./GTK/curl/tests/libtest/lib526.o \
./GTK/curl/tests/libtest/lib530.o \
./GTK/curl/tests/libtest/lib533.o \
./GTK/curl/tests/libtest/lib536.o \
./GTK/curl/tests/libtest/lib537.o \
./GTK/curl/tests/libtest/lib539.o \
./GTK/curl/tests/libtest/lib540.o \
./GTK/curl/tests/libtest/lib541.o \
./GTK/curl/tests/libtest/lib542.o \
./GTK/curl/tests/libtest/lib543.o \
./GTK/curl/tests/libtest/lib544.o \
./GTK/curl/tests/libtest/lib547.o \
./GTK/curl/tests/libtest/lib549.o \
./GTK/curl/tests/libtest/lib552.o \
./GTK/curl/tests/libtest/lib553.o \
./GTK/curl/tests/libtest/lib554.o \
./GTK/curl/tests/libtest/lib555.o \
./GTK/curl/tests/libtest/lib556.o \
./GTK/curl/tests/libtest/lib557.o \
./GTK/curl/tests/libtest/lib558.o \
./GTK/curl/tests/libtest/lib560.o \
./GTK/curl/tests/libtest/lib562.o \
./GTK/curl/tests/libtest/lib564.o \
./GTK/curl/tests/libtest/lib566.o \
./GTK/curl/tests/libtest/lib567.o \
./GTK/curl/tests/libtest/lib568.o \
./GTK/curl/tests/libtest/lib569.o \
./GTK/curl/tests/libtest/lib570.o \
./GTK/curl/tests/libtest/lib571.o \
./GTK/curl/tests/libtest/lib572.o \
./GTK/curl/tests/libtest/lib573.o \
./GTK/curl/tests/libtest/lib574.o \
./GTK/curl/tests/libtest/lib575.o \
./GTK/curl/tests/libtest/lib576.o \
./GTK/curl/tests/libtest/lib578.o \
./GTK/curl/tests/libtest/lib579.o \
./GTK/curl/tests/libtest/lib582.o \
./GTK/curl/tests/libtest/lib583.o \
./GTK/curl/tests/libtest/lib586.o \
./GTK/curl/tests/libtest/lib590.o \
./GTK/curl/tests/libtest/lib591.o \
./GTK/curl/tests/libtest/lib597.o \
./GTK/curl/tests/libtest/lib598.o \
./GTK/curl/tests/libtest/lib599.o \
./GTK/curl/tests/libtest/libauthretry.o \
./GTK/curl/tests/libtest/libntlmconnect.o \
./GTK/curl/tests/libtest/sethostname.o \
./GTK/curl/tests/libtest/testtrace.o \
./GTK/curl/tests/libtest/testutil.o 

C_DEPS += \
./GTK/curl/tests/libtest/chkhostname.d \
./GTK/curl/tests/libtest/first.d \
./GTK/curl/tests/libtest/lib1500.d \
./GTK/curl/tests/libtest/lib1501.d \
./GTK/curl/tests/libtest/lib1502.d \
./GTK/curl/tests/libtest/lib1506.d \
./GTK/curl/tests/libtest/lib1507.d \
./GTK/curl/tests/libtest/lib1508.d \
./GTK/curl/tests/libtest/lib1509.d \
./GTK/curl/tests/libtest/lib1510.d \
./GTK/curl/tests/libtest/lib1511.d \
./GTK/curl/tests/libtest/lib1512.d \
./GTK/curl/tests/libtest/lib1513.d \
./GTK/curl/tests/libtest/lib1514.d \
./GTK/curl/tests/libtest/lib1515.d \
./GTK/curl/tests/libtest/lib1520.d \
./GTK/curl/tests/libtest/lib1525.d \
./GTK/curl/tests/libtest/lib1526.d \
./GTK/curl/tests/libtest/lib1527.d \
./GTK/curl/tests/libtest/lib1528.d \
./GTK/curl/tests/libtest/lib1529.d \
./GTK/curl/tests/libtest/lib1530.d \
./GTK/curl/tests/libtest/lib1531.d \
./GTK/curl/tests/libtest/lib1900.d \
./GTK/curl/tests/libtest/lib500.d \
./GTK/curl/tests/libtest/lib501.d \
./GTK/curl/tests/libtest/lib502.d \
./GTK/curl/tests/libtest/lib503.d \
./GTK/curl/tests/libtest/lib504.d \
./GTK/curl/tests/libtest/lib505.d \
./GTK/curl/tests/libtest/lib506.d \
./GTK/curl/tests/libtest/lib507.d \
./GTK/curl/tests/libtest/lib508.d \
./GTK/curl/tests/libtest/lib509.d \
./GTK/curl/tests/libtest/lib510.d \
./GTK/curl/tests/libtest/lib511.d \
./GTK/curl/tests/libtest/lib512.d \
./GTK/curl/tests/libtest/lib513.d \
./GTK/curl/tests/libtest/lib514.d \
./GTK/curl/tests/libtest/lib515.d \
./GTK/curl/tests/libtest/lib516.d \
./GTK/curl/tests/libtest/lib517.d \
./GTK/curl/tests/libtest/lib518.d \
./GTK/curl/tests/libtest/lib519.d \
./GTK/curl/tests/libtest/lib520.d \
./GTK/curl/tests/libtest/lib521.d \
./GTK/curl/tests/libtest/lib523.d \
./GTK/curl/tests/libtest/lib524.d \
./GTK/curl/tests/libtest/lib525.d \
./GTK/curl/tests/libtest/lib526.d \
./GTK/curl/tests/libtest/lib530.d \
./GTK/curl/tests/libtest/lib533.d \
./GTK/curl/tests/libtest/lib536.d \
./GTK/curl/tests/libtest/lib537.d \
./GTK/curl/tests/libtest/lib539.d \
./GTK/curl/tests/libtest/lib540.d \
./GTK/curl/tests/libtest/lib541.d \
./GTK/curl/tests/libtest/lib542.d \
./GTK/curl/tests/libtest/lib543.d \
./GTK/curl/tests/libtest/lib544.d \
./GTK/curl/tests/libtest/lib547.d \
./GTK/curl/tests/libtest/lib549.d \
./GTK/curl/tests/libtest/lib552.d \
./GTK/curl/tests/libtest/lib553.d \
./GTK/curl/tests/libtest/lib554.d \
./GTK/curl/tests/libtest/lib555.d \
./GTK/curl/tests/libtest/lib556.d \
./GTK/curl/tests/libtest/lib557.d \
./GTK/curl/tests/libtest/lib558.d \
./GTK/curl/tests/libtest/lib560.d \
./GTK/curl/tests/libtest/lib562.d \
./GTK/curl/tests/libtest/lib564.d \
./GTK/curl/tests/libtest/lib566.d \
./GTK/curl/tests/libtest/lib567.d \
./GTK/curl/tests/libtest/lib568.d \
./GTK/curl/tests/libtest/lib569.d \
./GTK/curl/tests/libtest/lib570.d \
./GTK/curl/tests/libtest/lib571.d \
./GTK/curl/tests/libtest/lib572.d \
./GTK/curl/tests/libtest/lib573.d \
./GTK/curl/tests/libtest/lib574.d \
./GTK/curl/tests/libtest/lib575.d \
./GTK/curl/tests/libtest/lib576.d \
./GTK/curl/tests/libtest/lib578.d \
./GTK/curl/tests/libtest/lib579.d \
./GTK/curl/tests/libtest/lib582.d \
./GTK/curl/tests/libtest/lib583.d \
./GTK/curl/tests/libtest/lib586.d \
./GTK/curl/tests/libtest/lib590.d \
./GTK/curl/tests/libtest/lib591.d \
./GTK/curl/tests/libtest/lib597.d \
./GTK/curl/tests/libtest/lib598.d \
./GTK/curl/tests/libtest/lib599.d \
./GTK/curl/tests/libtest/libauthretry.d \
./GTK/curl/tests/libtest/libntlmconnect.d \
./GTK/curl/tests/libtest/sethostname.d \
./GTK/curl/tests/libtest/testtrace.d \
./GTK/curl/tests/libtest/testutil.d 


# Each subdirectory must supply rules for building sources it contributes
GTK/curl/tests/libtest/%.o: ../GTK/curl/tests/libtest/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	arm-linux-gnueabihf-gcc -I/home/snelso/rpi/rootfs/usr/include/gtk-3.0 -I/home/snelso/rpi/rootfs/usr/include/curl -I/home/snelso/capstone-workspace/ABRSEmbeddedDev/Teensy -I/home/snelso/rpi/rootfs/usr/include/at-spi2-atk/2.0 -I/home/snelso/rpi/rootfs/usr/include/atk-1.0 -I/home/snelso/rpi/rootfs/usr/include/harfbuzz -I/home/snelso/rpi/rootfs/usr/include/libpng12 -I/home/snelso/rpi/rootfs/usr/include/pixman-1 -I/home/snelso/rpi/rootfs/usr/include/gdk-pixbuf-2.0 -I/home/snelso/rpi/rootfs/usr/include/cairo -I/home/snelso/rpi/rootfs/usr/include/freetype2 -I/home/snelso/rpi/rootfs/usr/include/gio-unix-2.0/ -I/home/snelso/rpi/rootfs/usr/include/pango-1.0 -I/home/snelso/rpi/rootfs/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/home/snelso/rpi/rootfs/usr/include/glib-2.0 -I/home/snelso/capstone-workspace/ABRSEmbeddedDev/Deps/wiringPi/wiringPi-from-pi -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"  -lpthread -lwiringPi -lcurl
	@echo 'Finished building: $<'
	@echo ' '


